Nav baptiste
NAELIC/rostron_bringup pull request #4
Opened 2021-04-20 06:37 UTC by Bedeux

Update Config nav.yaml

2021-04-20 09:21 UTC, EtienneSchmitz requested changes

2021-04-20 09:21 UTC, EtienneSchmitz commented on params/nav.yaml
> +      yaw_goal_tolerance: 6.25 #0.1
Si l'unité est en radian, ce n'est pas un peu trop haut ?

2021-04-20 09:21 UTC, EtienneSchmitz commented on params/nav.yaml
> +    # DWB parameterss
Erreur parameters

2021-04-20 09:21 UTC, EtienneSchmitz commented on params/nav.yaml
> +      # Multiplicateur de 1.0875
Pas de commentaire en français

2021-04-20 09:21 UTC, EtienneSchmitz commented on params/nav.yaml
> +      movement_time_allowance: 10.0 #10.0
Si c'est pour garder les anciennes valeurs lors de tes tests, c'est ok les commentaire, mais lors du merge sur la branche develop, enlève les valeurs.

2021-04-20 09:21 UTC, EtienneSchmitz commented on params/nav.yaml
> +      min_vel_y: -5.5
Pourquoi ne pas mettre les même valeurs en x et en y ?

2021-04-20 09:21 UTC, EtienneSchmitz commented on params/nav.yaml
> +      min_speed_xy: -5.0
Je ne suis pas sûr de cette valeur, mais je pense qu'elle doit restreindre le robot a aller plus vite. As-tu testé de la mettre à 10m.s ?
J'ai peur que ça soit la valeur du vecteur xy ensemble, donc faut trouver à une vitesse maximale 6 en x et en y combien sera la valeur du vecteur xy (sa norme)

2021-04-20 09:21 UTC, EtienneSchmitz commented on params/nav.yaml
> +      decel_lim_x: -0.5
Pourquoi la déceleration n'est elle pas aussi haute que l'accélération ? (dans le sens négatif, ça serait plus basse)

2021-04-20 09:21 UTC, EtienneSchmitz commented on params/nav.yaml
> +      #Distance durant laquelle le robot accélère
Commentaire en français

2021-04-20 09:21 UTC, EtienneSchmitz commented on params/nav.yaml
> +      robot_radius: 0.085 #0.085
Le robot radius ne doit pas être changé (notre valeur)

2021-04-20 09:28 UTC, EtienneSchmitz commented on params/nav.yaml
> +      robot_radius: 0.085 #0.085
C'est une constante je voulais dire !

2021-04-20 15:56 UTC, Bedeux commented on params/nav.yaml
> +      yaw_goal_tolerance: 6.25 #0.1
Etant donné que mon robot ne fait sa rotation qu'à la fin, j'avais mis une tolérance de 2Pi pour que dès que j'arrive au point final, j'ai un return success. 
Une erreur que j'aurai pu rectifier en me relisant

2021-04-20 15:57 UTC, Bedeux commented on params/nav.yaml
> +      min_vel_y: -5.5
J'ai rectifié, j'avais changé car c'était plus précis bizarrement mais finalement avec la même valeur ca marche aussi

2021-04-20 16:02 UTC, Bedeux commented on params/nav.yaml
> +      decel_lim_x: -0.5
C'est le max de la deceleration, et la baisser permet d'aller plus vite à un point. En dessous ça ne fonctionne pas et au dessus ça rend le robot plus lent

2021-04-20 16:06 UTC, Bedeux commented on params/nav.yaml
> +      min_speed_xy: -5.0
Pour le coup j'ai testé pas mal de valeur, allant jusqu'à 100 (pour essayer ^^). Ca ne change pas grand chose. C'est comme si il y avait un blocage quelque part qui limitait la vitesse du robot mais pas dans les paramètres du DWB controller j'ai l'impression

2021-04-20 16:10 UTC, Bedeux commented on params/nav.yaml
> +      min_speed_xy: -5.0
J'ai essayé de prendre en compte ta remarque pour le vecteur xy, mais étant donné qu'on a pas accès aux coordonnées je sais pas comment on peut trouver sa norme. De même j'ai essayé d'augmenter : min_speed_xy et max_speed_xy et pas de changement notable (j'ai bien sûr changé avec des grosses valeurs à côté)

2021-04-20 16:58 UTC, EtienneSchmitz commented on params/nav.yaml
> +      min_speed_xy: -5.0
La norme d'un vecteur partant de 0,0 et de 6,6 qui est égale à ça :
```tex
\sqrt{6^{2}+6^{2}}=8.4852813742386
```
(Aucun moyen d'afficher une équation sous github)

2021-04-21 06:50 UTC, Bedeux commented on params/nav.yaml
> +      min_speed_xy: -5.0
Dans mon dernier commit j'ai tenté de faire une norme avec les vitesses, 
max_speed_xy= sqrt( (max_vel_x)² + (max_vel_x)² ) = 14.14
Pas sûr que ce soit ça étant donnée que ce ne sont pas des points. Mais cela fonctionne disons que mettre  plus en max_speed_xy ne fait pas de différence

2021-04-21 06:59 UTC, EtienneSchmitz commented on params/nav.yaml
> +      min_speed_xy: -5.0
Pour moi ça aurait du être la somme de deux vecteurs, je passe en résolu !

2021-04-21 06:59 UTC, EtienneSchmitz commented
Ready to merge ?

2021-04-21 07:45 UTC, Bedeux commented
Je pense que c'est bon oui

2021-04-21 07:50 UTC, merged